"""Tests for the GPU proxy trainer patcher (ffsim/gpu): pure-python pieces only (torch is not installed).

- the patcher applies every patch exactly `count` times, fails loudly on a missing / surplus anchor, and
  the committed ffsim/gpu/train_gpu.py is byte-identical to a fresh build of the K60 file;
- the generated file compiles, carries the provenance sha, refuses neuron, and embeds vclock/datasplit verbatim;
- the virtual clock reproduces the C40_cold_K59 chip-C switch steps (accum phases, MTP stages, cooldown
  levels) within +-2 steps and the exact step count from the log's per-phase means; medians drift as documented;
- env stripping / refusal decisions; data-split index arithmetic vs an explicit N-rank split.
"""
from __future__ import annotations

import os
import re
from pathlib import Path

import pytest

from ffsim.gpu import datasplit, gpu_env, make_train_gpu, vclock

REPO = Path(__file__).resolve().parents[1]
SOURCE = REPO / "recipes" / "K60" / "train.py"
GENERATED = REPO / "ffsim" / "gpu" / "train_gpu.py"
C40_LOG = REPO / "research" / "sim-data" / "chipC" / "C40_cold_K59" / "train.log"

needs_source = pytest.mark.skipif(not SOURCE.exists(), reason="K60 train.py not present")
needs_c40 = pytest.mark.skipif(not C40_LOG.exists(), reason="C40_cold_K59 train.log not harvested")


@pytest.fixture(scope="module")
def source_text() -> str:
    if not SOURCE.exists():
        pytest.skip("K60 train.py not present")
    return SOURCE.read_text(encoding="utf-8")


@pytest.fixture(scope="module")
def built(source_text):
    return make_train_gpu.build(source_text, "recipes/K60/train.py")


# ----------------------------------------------------------------------------------------------
# patcher
# ----------------------------------------------------------------------------------------------
@needs_source
def test_every_patch_applies_exactly_once(built):
    text, report = built
    names = [r["name"] for r in report]
    assert len(names) == len(set(names)) and len(names) >= 30
    assert all(r["delta_chars"] != 0 or r["mode"] == "replace" for r in report)
    for p in make_train_gpu.build_patches("", "x") if False else []:  # (build_patches needs the source; see below)
        pass
    # the anchors of the replace/insert patches are gone or still there exactly as the mode says
    for p in make_train_gpu.build_patches(SOURCE.read_text(encoding="utf-8"), "submission/x/train.py"):
        if p.mode == "prepend":
            continue
        if p.mode == "replace" and p.anchor not in p.replacement:
            assert p.anchor not in text, p.name
        else:
            assert text.count(p.anchor) == p.count, p.name


@needs_source
def test_generated_compiles_and_carries_provenance(built, source_text):
    text, _ = built
    compile(text, "train_gpu.py", "exec")
    sha = make_train_gpu.sha256_text(source_text)
    assert f'_GPU_SOURCE_SHA256 = "{sha}"' in text
    assert text.startswith("# GENERATED by ffsim/gpu/make_train_gpu.py")
    # neuron is refused at the device level and never a compile backend choice for the GPU
    assert 'raise SystemExit("train_gpu.py runs on cuda or cpu only' in text
    assert 'os.environ["NEURON_CC_FLAGS"]' not in text
    assert 'os.environ.setdefault("NEURON_RT_STOCHASTIC_ROUNDING_EN", "1")' not in text
    assert 'os.environ.setdefault("NEURON_RT_XU_COMPUTE_MAX_QUEUED_REQUESTS"' not in text
    # the learning-relevant pieces are untouched: the custom autograd Functions and the optimizer body
    for name in ("class _Relu2Fn(torch.autograd.Function):", "class _LeakySq(torch.autograd.Function):",
                 "class _FusedChunkedCE(torch.autograd.Function):", "class MuonAdamW(torch.optim.Optimizer):",
                 "def init_weights(self) -> None:", "def cooldown_level(progress: float) -> int:",
                 "def mtp_stage_of(progress: float) -> int:", "def accum_phase_of(next_step: int, progress: float) -> int:"):
        assert text.count(name) == 1 and source_text.count(name) == 1, name
    # the clock read is replaced exactly once, and every consumer of `charged` still reads `charged`
    assert text.count("charged = _GPU_VCLOCK.charged if _GPU_VCLOCK is not None else charged_wall") == 1
    assert "level_next = cooldown_level(charged / TIME_TARGET_SECONDS)" in text
    assert "mtp_stage_next = mtp_stage_of(charged / TIME_TARGET_SECONDS)" in text
    assert "step + 1, charged / TIME_TARGET_SECONDS if reached_min_steps else 0.0) if ACCUM_ON else 0" in text


@needs_source
def test_embedded_modules_are_verbatim(built):
    text, _ = built
    for mod in ("vclock.py", "datasplit.py"):
        body = (REPO / "ffsim" / "gpu" / mod).read_text(encoding="utf-8").rstrip()
        assert body in text, mod
        assert not re.search(r"^from __future__ import", body, re.M)


@needs_source
def test_committed_train_gpu_is_current(built):
    text, _ = built
    assert GENERATED.exists(), "run: python -m ffsim.gpu.make_train_gpu"
    assert GENERATED.read_text(encoding="utf-8") == text, "ffsim/gpu/train_gpu.py is stale: re-run the patcher"


@needs_source
def test_missing_anchor_fails_loudly(source_text):
    broken = source_text.replace("        charged = time.monotonic() - budget_started\n", "        charged = 0.0\n")
    with pytest.raises(make_train_gpu.PatchError, match="P25 charged read"):
        make_train_gpu.build(broken, "x/train.py")


@needs_source
def test_surplus_anchor_fails_loudly(source_text):
    doubled = source_text.replace("        dt = t_end - t0\n", "        dt = t_end - t0\n        dt = t_end - t0\n")
    with pytest.raises(make_train_gpu.PatchError, match="P24 virtual clock record"):
        make_train_gpu.build(doubled, "x/train.py")


@needs_source
def test_repatching_the_output_is_refused(built):
    text, _ = built
    with pytest.raises(make_train_gpu.PatchError):
        make_train_gpu.build(text, "x/train_gpu.py")


@needs_source
def test_source_defaults_extracted_from_the_file(source_text):
    d = make_train_gpu._source_defaults(source_text)
    assert d == {"FF_ATTN_SRC": "5:6,7,8", "FF_MUON_ZERO": "True", "FF_MUON_ZERO2": "True", "FF_ADAMW_ZERO": "True"}


# ----------------------------------------------------------------------------------------------
# virtual clock
# ----------------------------------------------------------------------------------------------
def test_recipe_from_env_reads_like_train_py():
    r = vclock.Recipe.from_env({"FF_TIME_TARGET": "1760", "FF_ACCUM_SCHED": "2:0.12,4", "FF_MTP": "0", "FF_COOLDOWN_FRAC": "0.45"})
    assert (r.time_target, r.mtp, r.cooldown_fraction) == (1760.0, 0, 0.45)
    assert r.accum == (2, 0.12, None, None, 4) and r.ks == [2, 4]
    assert vclock.Recipe.from_env({}).accum == (1, 0.06, 2, 0.2, 4)
    with pytest.raises(ValueError):
        vclock.vc_parse_accum_sched("1:0.06,2:0.2")


def test_clock_excludes_steps_0_to_4_and_mirrors_the_windows():
    vc = vclock.VirtualClock({4: 1.0, 1: 0.25})
    for s in range(7):
        vc.record(s, 4)
    assert vc.charged == 2.0 and len(vc.recent) == 7 and len(vc.steady) == 4
    vc.record(7, 1)
    assert vc.charged == 2.25 and vc.last_dt == 0.25
    with pytest.raises(KeyError, match="k=2"):
        vc.dt_for(2)


def test_parse_step_seconds_forms():
    assert vclock.parse_step_seconds("0.30,0.56,0.93", [1, 2, 4]) == {1: 0.30, 2: 0.56, 4: 0.93}
    assert vclock.parse_step_seconds("k4=0.93,k1=0.3", [1, 4]) == {4: 0.93, 1: 0.3}
    with pytest.raises(ValueError):
        vclock.parse_step_seconds("0.3,0.9", [1, 2, 4])


def test_walk_analytic_boundaries():
    # constant 1 s per step in every phase, TT 1000: k1 until 6% -> charged 60 -> after 15 warm-up + 45 k1 steps
    r = vclock.Recipe(time_target=1000.0)
    w = vclock.walk_schedule(r, {1: 1.0, 2: 1.0, 4: 1.0})
    assert w["accum"][0] == [1, 20, 15.0, 1]
    assert w["accum"][1][:2] == [2, 65]          # charged 60 reached after step 64 -> phase 2 from step 65
    assert w["accum"][2][:2] == [3, 205]         # 20% of 1000 = 200 s -> after step 204
    assert w["mtp"][0][:2] == [1, 55]            # 5% -> charged 50 -> after step 54
    assert w["levels"][0][:2] == [19, 405]       # cooldown starts at 40% -> 400 s -> after step 404
    # charged after step s is s - 4; stop when charged + est(1 s) + reserve(5 s) >= 1000 -> after step 998
    assert w["stop_reason"] == "clock" and w["steps"] == 999
    assert w["final_level"] == 1
    pinned = vclock.walk_schedule(r, {1: 1.0, 2: 1.0, 4: 1.0}, stop_step=500)
    assert pinned["steps"] == 500 and pinned["stop_reason"] == "stop_step" and pinned["levels"][-1][0] > 1


@needs_c40
def test_c40_log_parse():
    log = vclock.parse_chip_log(str(C40_LOG))
    assert log["steps"] == 2357 and log["time_target"] == 1793.0 and log["grad_accum_steps"] == 4
    assert log["accum"] == [[1, 20, 13.9, 1], [2, 336, 107.7, 2], [3, 828, 358.7, 4]]
    assert [m[:2] for m in log["mtp"]] == [[1, 276], [2, 477], [3, 653], [4, 828], [5, 948], [6, 1068], [7, 1189], [8, 1309]]
    assert log["levels"][0][:2] == [19, 1213] and log["levels"][-1][:2] == [1, 2304]
    assert log["charged_final"] == 1787.1
    assert log["median_by_k"] == {1: 0.2937, 2: 0.5069, 4: 0.9312}


@needs_c40
def test_virtual_clock_reproduces_c40_switch_steps_within_2():
    log = vclock.parse_chip_log(str(C40_LOG))
    means = vclock.phase_seconds_from_log(str(C40_LOG))
    assert means[1] == pytest.approx(0.2968, abs=2e-4) and means[2] == pytest.approx(0.5102, abs=2e-4) \
        and means[4] == pytest.approx(0.9341, abs=2e-4)
    walk = vclock.walk_schedule(vclock.Recipe(), means)
    cmp = vclock.compare_schedules(walk, log)
    assert not cmp["missing"]
    assert cmp["max_abs_switch_diff"] <= 2, vclock.format_comparison(cmp)
    assert cmp["steps_diff"] == 0 and walk["stop_reason"] == "clock"
    assert walk["charged_final"] == pytest.approx(1787.1, abs=0.2)
    # the shipped default triple is the same C40 means
    walk_default = vclock.walk_schedule(vclock.Recipe(), vclock.DEFAULT_STEP_SECONDS)
    assert walk_default["steps"] == 2357 and walk_default["accum"] == walk["accum"]


@needs_c40
def test_medians_drift_late_switches_as_documented():
    log = vclock.parse_chip_log(str(C40_LOG))
    walk = vclock.walk_schedule(vclock.Recipe(), log["median_by_k"])
    cmp = vclock.compare_schedules(walk, log)
    # medians run 0.3-1% under the means: switches late by a few steps, the stop by ~0.5% (12 of 2357)
    assert 3 <= cmp["max_abs_switch_diff"] <= 15 and 5 <= cmp["steps_diff"] <= 20
    pinned = vclock.walk_schedule(vclock.Recipe(), log["median_by_k"], stop_step=2357)
    assert pinned["steps"] == 2357 and pinned["stop_reason"] == "stop_step"


@needs_c40
def test_rescale_to_steps_hits_the_target_and_keeps_fractions():
    means = vclock.phase_seconds_from_log(str(C40_LOG))
    r = vclock.Recipe()
    for target in (2361, 2340, 2314, 2200):
        scaled, scale, walk = vclock.rescale_to_steps(r, means, target)
        assert walk["steps"] == target and walk["stop_reason"] == "stop_step"
        # the clock-driven stop lands on the target too (the pin never truncates a longer schedule)
        assert vclock.walk_schedule(r, scaled)["steps"] == target
        assert scale == pytest.approx(2357 / target, rel=0.02)
        # switches sit at the same charged FRACTION: phase 2 at 6%, phase 3 / MTP stage 4 at 20%, level 19 at 40%
        assert walk["accum"][1][2] == pytest.approx(0.06 * 1793, abs=0.6)
        assert walk["accum"][2][2] == pytest.approx(0.20 * 1793, abs=1.0)
        assert walk["levels"][0][2] == pytest.approx(0.40 * 1793, abs=1.0)
        assert walk["final_level"] == 1
    with pytest.raises(ValueError):
        vclock.rescale_to_steps(r, means, 50)


@needs_source
def test_generated_has_the_fleet_contract_flags(built):
    text, _ = built
    for flag in ('"--steps"', '"--stop-step"', '"--clock"', '"--step-seconds"', '"--data-world"', '"--results"',
                 '"--label"', '"--arm"', '"--pair"', '"--eval-emulate-ranks"', '"--dry-run"', '"--compare-log"',
                 '"--device-type", "--device"', '"--compile", type=str, default="inductor", choices=["inductor", "none"]'):
        assert flag in text, flag
    assert 'globals()["ACC_IN_GRAPH"] = 0' in text            # --compile none: eager accumulation, recorded
    assert '"acc_in_graph_disabled": _GPU_ACC_IN_GRAPH_DISABLED[0]' in text
    assert '"clock_scale": _GPU_CLOCK_SCALE[0]' in text


# ----------------------------------------------------------------------------------------------
# env
# ----------------------------------------------------------------------------------------------
def test_env_verdicts():
    assert gpu_env.classify("FF_CC_FLAGS", "-O3")[0] == "refuse"
    assert gpu_env.classify("FF_HOST_TIMES", "1")[0] == "refuse"
    assert gpu_env.classify("FF_HOST_TIMES", "0")[0] == "strip"          # off value: inert, tolerated
    assert gpu_env.classify("FF_XU_QUEUE", "0")[0] == "strip"
    assert gpu_env.classify("FF_XU_QUEUE", "32")[0] == "refuse"
    assert gpu_env.classify("FF_BF16_PARAMS", "1")[0] == "refuse"
    assert gpu_env.classify("FF_NKI_ATTN", "1")[0] == "refuse"
    assert gpu_env.classify("FF_COMPILE_OPT", "1")[0] == "refuse"
    assert gpu_env.classify("FF_TIMEOUT", "2700")[0] == "strip"
    assert gpu_env.classify("NEURON_COMPETITION_R1_COMPILE", "1")[0] == "strip"
    assert gpu_env.classify("NEURON_COMPETITION_R1_NUM_STEPS", "10")[0] == "refuse"
    assert gpu_env.classify("NEURON_RT_STOCHASTIC_ROUNDING_EN", "0")[0] == "refuse"
    assert gpu_env.classify("NEURON_COMPETITION_R1_CACHE_DIR", "/x") == ("", "")
    assert gpu_env.classify("NEURON_FOO", "1")[0] == "refuse"
    for name in ("FF_TIME_TARGET", "FF_EMA", "FF_SEED", "FF_KV_SDPA", "FF_ATTN_SRC", "FF_ACC_IN_GRAPH", "FF_MUON_ZERO2",
                 "FF_ADAMW_ZERO", "FF_ASYNC_SYNC", "FF_SCHEDULE", "FF_STEP_TOTAL", "FF_UNKNOWN_NEW_KNOB"):
        assert gpu_env.classify(name, "1") == ("", ""), name


def test_strip_and_refuse_on_a_real_queue_env():
    overrides = REPO / "research" / "sim-data" / "chipC" / "1639_R_m14asa_s73" / "overrides"
    if not overrides.exists():
        pytest.skip("chip C overrides not harvested")
    env = gpu_env.parse_env_file(overrides.read_text(encoding="utf-8"))
    env.update({"NEURON_RT_STOCHASTIC_ROUNDING_EN": "0", "NEURON_COMPETITION_R1_CACHE_DIR": "/data", "FF_HOST_TIMES": "1"})
    kept, removed = gpu_env.strip(env)
    assert {"FF_CC_FLAGS", "FF_TIMEOUT", "NEURON_COMPETITION_R1_COMPILE", "NEURON_RT_STOCHASTIC_ROUNDING_EN", "FF_HOST_TIMES"} <= set(removed)
    assert {"FF_TIME_TARGET", "FF_EMA", "FF_SEED", "FF_ATTN_SRC", "NEURON_COMPETITION_R1_CACHE_DIR", "FF_MUON_ZERO2"} <= set(kept)
    assert removed["FF_COMPILE_SYNC"].startswith("strip:")               # FF_COMPILE_SYNC=0 on the chip: inert
    assert "FF_XU_QUEUE" in removed                                       # the queue env sets it (32): a Neuron runtime knob
    with pytest.raises(SystemExit) as ei:
        gpu_env.refuse(env)
    msg = str(ei.value)
    assert "FF_CC_FLAGS" in msg and "FF_HOST_TIMES" in msg and "NEURON_RT_STOCHASTIC_ROUNDING_EN" in msg
    assert "FF_TIMEOUT" not in msg and "FF_COMPILE_SYNC" not in msg     # tolerated, not refused
    gpu_env.refuse(kept)                                                  # what fleet passes on is accepted


@needs_source
def test_generated_refusal_table_matches_gpu_env(built):
    text, _ = built
    assert f"_GPU_REFUSED = {gpu_env.REFUSED!r}" in text
    assert f"_GPU_STRIPPED = {gpu_env.STRIPPED!r}" in text
    assert f"_GPU_REFUSED_PREFIXES = {gpu_env.REFUSED_PREFIXES!r}" in text
    assert f"_GPU_ALLOWED_NEURON = {tuple(gpu_env.ALLOWED_NEURON)!r}" in text


def test_notes_table_covers_every_refused_name():
    names = {row[0] for row in gpu_env.notes_table()}
    assert set(gpu_env.REFUSED) <= names and set(gpu_env.STRIPPED) <= names


# ----------------------------------------------------------------------------------------------
# data split
# ----------------------------------------------------------------------------------------------
@pytest.mark.parametrize("shares", [8, 4, 2, 1])
def test_data_world_fetch_order_matches_an_explicit_rank_split(shares):
    ks = [4] * 20 + [1] * 30 + [2] * 30 + [4] * 12
    emulated = datasplit.emulated_fetch_order(ks, shares)
    reference = datasplit.trainium_step_rows(ks, shares)
    assert len(emulated) == len(ks)
    for step, (a, b) in enumerate(zip(emulated, reference)):
        assert len(a) == ks[step] * shares
        assert sorted(a) == sorted(b), step            # same rows per optimizer step
        assert a == sorted(a)                          # share by share, each share in its own order
    for s in range(shares):                            # every share's generator is consumed in order
        seq = [m for step in emulated for (sh, m) in step if sh == s]
        assert seq == list(range(len(seq)))


def test_share_cursor_rules():
    c = datasplit.ShareCursor(8, 4)
    assert [c.next_share() for _ in range(32)] == [j // 4 for j in range(32)]
    assert c.j == 0
    c.next_share()                     # the prefetched micro 0 of the next step (share 0 whatever k is)
    c.set_k(1)                         # allowed right after that prefetch
    assert [c.next_share() for _ in range(7)] == list(range(1, 8)) and c.j == 0
    c.next_share(); c.next_share()
    with pytest.raises(RuntimeError, match="mid-step"):
        c.set_k(4)
    with pytest.raises(ValueError):
        datasplit.ShareCursor(0, 4)


def test_grad_scale_identity():
    assert datasplit.grad_scale_matches(4, 8) and datasplit.grad_scale_matches(1, 8) and datasplit.grad_scale_matches(2, 4, 2)


@needs_source
def test_generated_loss_seeds_and_micro_counts_use_shares(built):
    text, _ = built
    assert text.count("backward_scaled(loss, grad_accum_steps)") == 0
    assert text.count("backward_scaled(loss, grad_accum_steps * _GPU_SHARES)") == 3   # 2 patched + the dry-run's
    assert "loss_seed(loss, k * _GPU_SHARES) for k in (ACCUM_K0, ACCUM_K1, ACCUM_K_FINAL)" in text
    assert "micro_n = step_k * _GPU_SHARES" in text and "for micro in range(micro_n):" in text
    assert "world_tokens_per_micro = DEVICE_BATCH_SIZE * TRAIN_SEQ * _GPU_DATA_WORLD" in text
    assert "accum_micro_done += step_k" in text            # the Muon momentum ramp still counts Trainium micro-batches
