"""Shared helpers for the paper's analysis scripts.

Every number the paper prints is registered here as a named value and written to ``paper/numbers.tex`` as

    \\ffdef{key}{value}

and used in the text as ``\\val{key}``. Tables are written to ``paper/tables/*.tex``. Nothing in ``paper/`` that a
script writes is meant to be edited by hand: rerun ``python paper/analysis/make_all.py`` instead.

Keys are lower-case letters, digits and hyphens. A value is LaTeX text-mode material (signs are written with
``\\ensuremath{-}`` / ``\\ensuremath{+}`` so a negative number never prints as a hyphen).
"""
from __future__ import annotations

import csv
import json
import math
import re
import sys
from pathlib import Path
from typing import Dict, List, Optional

ROOT = Path(__file__).resolve().parents[2]
PAPER = ROOT / "paper"
TABLES = PAPER / "tables"
FIGURES = PAPER / "figures"
SCORES = ROOT / "results" / "official-scores.csv"
UPLOADS = ROOT / "research" / "sim-data" / "official-uploads.csv"
RUNS = ROOT / "research" / "sim-data" / "runs.jsonl"
PAIRS = ROOT / "research" / "sim-data" / "validation-pairs.json"
RECIPE_K82S4 = ROOT / "ffsim" / "examples" / "recipe-K82s4.json"

if str(ROOT) not in sys.path:
    sys.path.insert(0, str(ROOT))

_KEY = re.compile(r"^[a-z0-9]+(?:-[a-z0-9]+)*$")


class Numbers:
    """An ordered registry of named values for ``numbers.tex``."""

    def __init__(self) -> None:
        self.values: Dict[str, str] = {}
        self.sources: Dict[str, str] = {}

    def add(self, key: str, value: str, source: str = "") -> str:
        if not _KEY.match(key):
            raise ValueError(f"bad key {key!r}: use lower-case letters, digits and hyphens")
        if key in self.values and self.values[key] != value:
            raise ValueError(f"key {key!r} defined twice with different values: {self.values[key]!r} vs {value!r}")
        self.values[key] = value
        self.sources[key] = source
        return value

    def write(self, path: Path) -> None:
        lines = ["% numbers.tex -- GENERATED by paper/analysis/make_all.py; do not edit by hand.",
                 "% Each value: \\ffdef{key}{value}; used in the text as \\val{key}. The comment names the source.", ""]
        for k, v in self.values.items():
            src = self.sources.get(k, "")
            lines.append(f"\\ffdef{{{k}}}{{{v}}}" + (f"  % {src}" if src else ""))
        write_text(path, "\n".join(lines) + "\n")


def write_text(path: Path, text: str) -> None:
    path.parent.mkdir(parents=True, exist_ok=True)
    with open(path, "w", encoding="utf-8", newline="\n") as fh:
        fh.write(text)


# ------------------------------------------------------------------------------------------- formatting
def num(x: float, nd: int = 4, sign: bool = False, strip_zero: bool = False) -> str:
    """LaTeX text for a number: fixed ``nd`` decimals, a real minus sign, ``+`` when ``sign``."""
    if x is None or (isinstance(x, float) and not math.isfinite(x)):
        return "n/a"
    s = f"{abs(x):.{nd}f}"
    if strip_zero and s.startswith("0."):
        s = s[1:]
    if x < 0 and float(s) != 0.0:
        return "\\ensuremath{-}" + s
    if sign and float(s) != 0.0:
        return "\\ensuremath{+}" + s
    return s


def pct(x: float, nd: int = 1, sign: bool = False) -> str:
    """A fraction as a percentage, e.g. 0.848 -> 84.8\\%."""
    return num(100.0 * x, nd, sign) + "\\%"


def intc(n: float) -> str:
    """An integer with a thin-space thousands separator (2{,}388)."""
    return f"{int(round(n)):,}".replace(",", "{,}")


def milli(x: float, nd: int = 2, sign: bool = False) -> str:
    """x in units of 1e-3, for tables headed 'x 10^-3'."""
    return num(1e3 * x, nd, sign)


def tex_escape(s: str) -> str:
    """Escape LaTeX special characters in free text (for names copied from the data files)."""
    s = s.replace("^2", "²")
    rep = {"\\": "\\textbackslash{}", "&": "\\&", "%": "\\%", "$": "\\$", "#": "\\#", "_": "\\_",
           "{": "\\{", "}": "\\}", "~": "\\textasciitilde{}", "^": "\\textasciicircum{}"}
    out = "".join(rep.get(c, c) for c in s)
    out = out.replace("->", "$\\rightarrow$").replace("<=", "$\\le$").replace(">=", "$\\ge$")
    out = out.replace("\u2212", "\\ensuremath{-}").replace("\u00b2", "\\textsuperscript{2}")
    out = out.replace("\u00d7", "$\\times$").replace("\u2248", "$\\approx$")
    return out


def table(path: Path, body_lines: List[str], colspec: str, header: str, caption_comment: str = "",
          size: str = "\\small", tabcolsep: str = "") -> None:
    """A booktabs tabular (no float wrapper: the section file owns the float, caption and label)."""
    sep = f"\\setlength{{\\tabcolsep}}{{{tabcolsep}}}" if tabcolsep else ""
    lines = [f"% GENERATED by paper/analysis -- {caption_comment}".rstrip(), "{" + size + sep,
             f"\\begin{{tabular}}{{{colspec}}}", "\\toprule", header + " \\\\", "\\midrule"]
    lines += body_lines
    lines += ["\\bottomrule", "\\end{tabular}", "}"]
    write_text(path, "\n".join(lines) + "\n")


# ------------------------------------------------------------------------------------------- data
def official_str(v: float) -> str:
    """An official score as published: its own precision, at least four decimals (0.9620, 0.9613617)."""
    s = f"{v:.7f}".rstrip("0")
    whole, _, frac = s.partition(".")
    return f"{whole}.{frac.ljust(4, '0')}"


def offset_str(official: float, rehearsal: float, nd: int = 4) -> str:
    """official - rehearsal rounded HALF-UP from the exact decimal values (0.9712 - 0.96515 = 0.00605 -> +0.0061),
    the rule results/official-scores.csv uses. Binary floats would round 0.00605 down."""
    from decimal import ROUND_HALF_UP, Decimal
    d = (Decimal(repr(official)) - Decimal(repr(rehearsal))).quantize(Decimal(1).scaleb(-nd), rounding=ROUND_HALF_UP)
    return num(float(d), nd, sign=True)


def binom_tail(k: int, n: int) -> float:
    """P(X >= k) for X ~ Binomial(n, 1/2): a one-sided sign test."""
    return sum(math.comb(n, i) for i in range(k, n + 1)) / 2.0 ** n


def _f(v: Optional[str]) -> Optional[float]:
    v = (v or "").strip()
    return float(v) if v else None


def load_scores() -> List[dict]:
    rows = []
    with open(SCORES, newline="", encoding="utf-8") as fh:
        for r in csv.DictReader(fh):
            rows.append({
                "name": r["submission"].strip(),
                "date": r["uploaded_cdt"].strip(),
                "chip": r["rehearsal_chip"].strip(),
                "rehearsal": _f(r["rehearsal_bpb"]),
                "steps": _f(r["rehearsal_steps"]),
                "official": _f(r["official_bpb"]),
                "best": r["best_so_far"].strip() == "yes",
                "note": r["change_vs_previous_best"].strip(),
            })
    return rows


def load_pairs() -> List[dict]:
    return json.loads(PAIRS.read_text(encoding="utf-8"))


def mean(xs) -> float:
    xs = list(xs)
    return sum(xs) / len(xs)


def sd(xs) -> float:
    xs = list(xs)
    m = mean(xs)
    return math.sqrt(sum((x - m) ** 2 for x in xs) / (len(xs) - 1))


def t_quantile(p: float, df: int) -> float:
    """Student-t quantile by bisection on the regularised incomplete beta (scipy-free)."""
    def cdf(t: float) -> float:
        x = df / (df + t * t)
        ib = _betainc(df / 2.0, 0.5, x)
        return 1.0 - 0.5 * ib if t > 0 else 0.5 * ib
    lo, hi = -50.0, 50.0
    for _ in range(200):
        mid = 0.5 * (lo + hi)
        if cdf(mid) < p:
            lo = mid
        else:
            hi = mid
    return 0.5 * (lo + hi)


def _betainc(a: float, b: float, x: float) -> float:
    """Regularised incomplete beta I_x(a, b) (Numerical Recipes continued fraction)."""
    if x <= 0.0:
        return 0.0
    if x >= 1.0:
        return 1.0
    lbeta = math.lgamma(a + b) - math.lgamma(a) - math.lgamma(b) + a * math.log(x) + b * math.log(1.0 - x)
    front = math.exp(lbeta)
    if x < (a + 1.0) / (a + b + 2.0):
        return front * _betacf(a, b, x) / a
    return 1.0 - front * _betacf(b, a, 1.0 - x) / b


def _betacf(a: float, b: float, x: float) -> float:
    qab, qap, qam = a + b, a + 1.0, a - 1.0
    c, d = 1.0, 1.0 - qab * x / qap
    d = 1.0 / (d if abs(d) > 1e-300 else 1e-300)
    h = d
    for m in range(1, 300):
        m2 = 2 * m
        aa = m * (b - m) * x / ((qam + m2) * (a + m2))
        d = 1.0 + aa * d
        d = 1.0 / (d if abs(d) > 1e-300 else 1e-300)
        c = 1.0 + aa / c
        c = c if abs(c) > 1e-300 else 1e-300
        h *= d * c
        aa = -(a + m) * (qab + m) * x / ((a + m2) * (qap + m2))
        d = 1.0 + aa * d
        d = 1.0 / (d if abs(d) > 1e-300 else 1e-300)
        c = 1.0 + aa / c
        c = c if abs(c) > 1e-300 else 1e-300
        de = d * c
        h *= de
        if abs(de - 1.0) < 1e-12:
            break
    return h


def wilson(k: int, n: int, z: float = 1.959964) -> tuple:
    """Wilson score interval for a binomial proportion."""
    if n == 0:
        return (float("nan"), float("nan"))
    p = k / n
    den = 1 + z * z / n
    centre = (p + z * z / (2 * n)) / den
    half = z * math.sqrt(p * (1 - p) / n + z * z / (4 * n * n)) / den
    return centre - half, centre + half
