"""Regenerate every number, table and paper-only figure from the repository's data.

    python paper/analysis/make_all.py

Writes paper/numbers.tex (\\ffdef{key}{value} for every number the text prints), paper/tables/*.tex and
paper/figures/*.pdf. The shared figures (docs/figures/paper/*.pdf) come from
``python docs/figures/make_figures.py --paper``. Deterministic: no clock, fixed RNG seeds.
"""
from __future__ import annotations

import json
import sys
from pathlib import Path

HERE = Path(__file__).resolve().parent
sys.path.insert(0, str(HERE))

from common import PAPER, RECIPE_K82S4, TABLES, Numbers, intc, table, tex_escape  # noqa: E402

import contrib_guard  # noqa: E402
import docfacts  # noqa: E402
import exchange  # noqa: E402
import figs  # noqa: E402
import oracle  # noqa: E402
import seeds  # noqa: E402
import simulator  # noqa: E402

# (knob, what it sets) for the appendix hyperparameter table; values are read from ffsim/examples/recipe-K82s4.json
HYPER = [
    ("FF_DEPTH", "transformer blocks"),
    ("FF_ASPECT_RATIO", "width = aspect $\\times$ depth, rounded to the head size (1{,}024)"),
    ("FF_HEAD_DIM", "query head size (four query heads)"),
    ("FF_KV_HEADS", "key/value heads (grouped-query attention)"),
    ("FF_MLP_MULT", "MLP expansion"),
    ("FF_LEAKY_RELU2", "LeakyReLU$^2$ negative slope"),
    ("FF_VALUE_EMBED", "value embeddings (fed to blocks 0 and 8)"),
    ("FF_ATTN_SRC", "attention-source reuse: blocks 6, 7, 8 reuse block 5"),
    ("FF_KEY_OFFSET_RAD", "rotary key-offset radius"),
    ("FF_ROPE_BASE", "RoPE base"),
    ("FF_SOFTCAP", "logit soft cap"),
    ("FF_TRAIN_SEQ", "sequence length (tokens)"),
    ("FF_MTP_W", "multi-token prediction weights (next, +2, +3)"),
    ("FF_MTP_PHASES", "MTP fade: start and end as fractions of the run"),
    ("FF_TOTAL_BATCH", "final batch (tokens per optimizer step)"),
    ("FF_MB", "micro-batch (sequences per rank)"),
    ("FF_ACCUM_SCHED", "batch warm-up: $k$ micro-batches until a time fraction"),
    ("FF_ACCUM_LR", "LR multipliers of the two small-batch phases"),
    ("FF_TIME_TARGET", "charged-time target (s)"),
    ("FF_WARMUP", "LR warm-up steps"),
    ("FF_COOLDOWN_FRAC", "linear cooldown, fraction of the run"),
    ("FF_MATRIX_LR_SCALE", "Muon LR scale (matrices)"),
    ("FF_ADAMW_LR_SCALE", "AdamW LR scale (embeddings, scalars, head)"),
    ("FF_EMB_LR", "embedding LR"),
    ("FF_UNEMB_LR", "output-head LR"),
    ("FF_SCALAR_LR", "scalar-parameter LR"),
    ("FF_MLP_PROJ_LR", "MLP output-projection LR multiplier"),
    ("FF_WD", "weight decay"),
    ("FF_MOM_PEAK", "Muon momentum peak"),
    ("FF_NS_STEPS", "Newton--Schulz iterations"),
    ("FF_OPT_FUSE", "fused optimizer update level"),
    ("FF_XU_QUEUE", "execution-queue depth"),
    ("FF_ROW_SHUFFLE", "row pool size (micro-batches)"),
    ("FF_ROW_SHUFFLE_FROM", "row pool starts at this micro-batch"),
    ("FF_EMA_EVERY", "EMA update interval (steps)"),
    ("FF_EMA_BLEND", "final weights: blend of live and EMA weights"),
    ("FF_EMA_PREWARM", "compile the EMA update during excluded startup"),
    ("FF_SEED", "training seed"),
]


def hyperparams(N: Numbers) -> None:
    d = json.loads(RECIPE_K82S4.read_text(encoding="utf-8"))
    knobs = d["knobs"]
    body = []
    for k, what in HYPER:
        v = knobs[k]
        body.append(f"\\texttt{{{tex_escape(k)}}} & \\texttt{{{tex_escape(v)}}} & {what} \\\\")
    table(TABLES / "hyperparams.tex", body, "@{}lp{3.2cm}p{7.6cm}@{}", "Knob & Value & Meaning",
          "ffsim/examples/recipe-K82s4.json (make_all.py)", size="\\footnotesize")
    N.add("k82-nknobs", str(len(knobs)), "ffsim/examples/recipe-K82s4.json")
    size = (PAPER.parent / "recipes" / "K82s4" / "train.py").stat().st_size
    N.add("k82-bytes", intc(size), "recipes/K82s4/train.py")


def docfacts_table(N: Numbers) -> None:
    """Appendix: every value quoted from a campaign document (source comment ends in "(doc)"), as a longtable."""
    from common import write_text
    rows = []
    for k, v in N.values.items():
        src = N.sources.get(k, "")
        if "(doc)" not in src:
            continue
        rows.append((src.replace(" (doc)", "").strip(), v, k))
    rows.sort(key=lambda r: (r[0].split(":")[0].split(" ")[0], r[2]))
    lines = ["% GENERATED by paper/analysis/make_all.py -- values quoted from campaign documents",
             r"\begin{longtable}{@{}p{3.6cm}p{12.0cm}@{}}",
             r"\caption{\textbf{Values quoted from campaign documents} (marked \docnum{} in the text).}"
             r"\label{tab:docfacts}\\",
             r"\toprule", r"Value & Source (document, section: what) \\", r"\midrule", r"\endfirsthead",
             r"\toprule", r"Value & Source (continued) \\", r"\midrule", r"\endhead",
             r"\bottomrule", r"\endlastfoot"]
    for src, v, k in rows:
        lines.append(f"{v} & {tex_escape(src)} \\\\")
    lines.append(r"\end{longtable}")
    write_text(TABLES / "docfacts.tex", "\n".join(lines) + "\n")
    N.add("n-docfacts", str(len(rows)), "make_all.py")


def main() -> int:
    N = Numbers()
    o = oracle.run(N)
    sim = simulator.run(N)
    sd_ = seeds.run(N)
    exchange.run(N)
    exchange.vague_prices(N, *sim["kappa_vague"])
    oracle.winners_curse(N, o, sd_["jitter_rel"], exchange.KAPPA)
    contrib_guard.run(N)
    docfacts.run(N)
    figs.run(N)
    hyperparams(N)
    docfacts_table(N)
    N.write(PAPER / "numbers.tex")
    print(f"numbers.tex: {len(N.values)} values; tables: {len(list(TABLES.glob('*.tex')))} files")
    return 0


if __name__ == "__main__":
    raise SystemExit(main())
